// World countries with international dialing codes (Russian names).
// Used by the profile form: country datalist + phone dial code / mask.
// Phone mask: dial '7' (KZ/RU) uses the grouped +7 (###) ###-##-## format;
// every other country uses a generic grouped format.

export type Country = { name: string; dial: string }

// Unsorted source — exported list is sorted alphabetically (ru) at module load.
const RAW: Country[] = [
  { name: 'Австралия', dial: '61' },
  { name: 'Австрия', dial: '43' },
  { name: 'Азербайджан', dial: '994' },
  { name: 'Албания', dial: '355' },
  { name: 'Алжир', dial: '213' },
  { name: 'Ангола', dial: '244' },
  { name: 'Андорра', dial: '376' },
  { name: 'Антигуа и Барбуда', dial: '1268' },
  { name: 'Аргентина', dial: '54' },
  { name: 'Армения', dial: '374' },
  { name: 'Афганистан', dial: '93' },
  { name: 'Багамы', dial: '1242' },
  { name: 'Бангладеш', dial: '880' },
  { name: 'Барбадос', dial: '1246' },
  { name: 'Бахрейн', dial: '973' },
  { name: 'Беларусь', dial: '375' },
  { name: 'Белиз', dial: '501' },
  { name: 'Бельгия', dial: '32' },
  { name: 'Бенин', dial: '229' },
  { name: 'Болгария', dial: '359' },
  { name: 'Боливия', dial: '591' },
  { name: 'Босния и Герцеговина', dial: '387' },
  { name: 'Ботсвана', dial: '267' },
  { name: 'Бразилия', dial: '55' },
  { name: 'Бруней', dial: '673' },
  { name: 'Буркина-Фасо', dial: '226' },
  { name: 'Бурунди', dial: '257' },
  { name: 'Бутан', dial: '975' },
  { name: 'Вануату', dial: '678' },
  { name: 'Ватикан', dial: '379' },
  { name: 'Великобритания', dial: '44' },
  { name: 'Венгрия', dial: '36' },
  { name: 'Венесуэла', dial: '58' },
  { name: 'Восточный Тимор', dial: '670' },
  { name: 'Вьетнам', dial: '84' },
  { name: 'Габон', dial: '241' },
  { name: 'Гаити', dial: '509' },
  { name: 'Гайана', dial: '592' },
  { name: 'Гамбия', dial: '220' },
  { name: 'Гана', dial: '233' },
  { name: 'Гватемала', dial: '502' },
  { name: 'Гвинея', dial: '224' },
  { name: 'Гвинея-Бисау', dial: '245' },
  { name: 'Германия', dial: '49' },
  { name: 'Гондурас', dial: '504' },
  { name: 'Гренада', dial: '1473' },
  { name: 'Греция', dial: '30' },
  { name: 'Грузия', dial: '995' },
  { name: 'Дания', dial: '45' },
  { name: 'Джибути', dial: '253' },
  { name: 'Доминика', dial: '1767' },
  { name: 'Доминиканская Республика', dial: '1809' },
  { name: 'Египет', dial: '20' },
  { name: 'Замбия', dial: '260' },
  { name: 'Зимбабве', dial: '263' },
  { name: 'Израиль', dial: '972' },
  { name: 'Индия', dial: '91' },
  { name: 'Индонезия', dial: '62' },
  { name: 'Иордания', dial: '962' },
  { name: 'Ирак', dial: '964' },
  { name: 'Иран', dial: '98' },
  { name: 'Ирландия', dial: '353' },
  { name: 'Исландия', dial: '354' },
  { name: 'Испания', dial: '34' },
  { name: 'Италия', dial: '39' },
  { name: 'Йемен', dial: '967' },
  { name: 'Кабо-Верде', dial: '238' },
  { name: 'Казахстан', dial: '7' },
  { name: 'Камбоджа', dial: '855' },
  { name: 'Камерун', dial: '237' },
  { name: 'Канада', dial: '1' },
  { name: 'Катар', dial: '974' },
  { name: 'Кения', dial: '254' },
  { name: 'Кипр', dial: '357' },
  { name: 'Киргизия', dial: '996' },
  { name: 'Кирибати', dial: '686' },
  { name: 'Китай', dial: '86' },
  { name: 'Колумбия', dial: '57' },
  { name: 'Коморы', dial: '269' },
  { name: 'Конго', dial: '242' },
  { name: 'ДР Конго', dial: '243' },
  { name: 'Коста-Рика', dial: '506' },
  { name: 'Кот-д’Ивуар', dial: '225' },
  { name: 'Куба', dial: '53' },
  { name: 'Кувейт', dial: '965' },
  { name: 'Лаос', dial: '856' },
  { name: 'Латвия', dial: '371' },
  { name: 'Лесото', dial: '266' },
  { name: 'Либерия', dial: '231' },
  { name: 'Ливан', dial: '961' },
  { name: 'Ливия', dial: '218' },
  { name: 'Литва', dial: '370' },
  { name: 'Лихтенштейн', dial: '423' },
  { name: 'Люксембург', dial: '352' },
  { name: 'Маврикий', dial: '230' },
  { name: 'Мавритания', dial: '222' },
  { name: 'Мадагаскар', dial: '261' },
  { name: 'Малави', dial: '265' },
  { name: 'Малайзия', dial: '60' },
  { name: 'Мали', dial: '223' },
  { name: 'Мальдивы', dial: '960' },
  { name: 'Мальта', dial: '356' },
  { name: 'Марокко', dial: '212' },
  { name: 'Маршалловы Острова', dial: '692' },
  { name: 'Мексика', dial: '52' },
  { name: 'Мозамбик', dial: '258' },
  { name: 'Молдова', dial: '373' },
  { name: 'Монако', dial: '377' },
  { name: 'Монголия', dial: '976' },
  { name: 'Мьянма', dial: '95' },
  { name: 'Намибия', dial: '264' },
  { name: 'Науру', dial: '674' },
  { name: 'Непал', dial: '977' },
  { name: 'Нигер', dial: '227' },
  { name: 'Нигерия', dial: '234' },
  { name: 'Нидерланды', dial: '31' },
  { name: 'Никарагуа', dial: '505' },
  { name: 'Новая Зеландия', dial: '64' },
  { name: 'Норвегия', dial: '47' },
  { name: 'ОАЭ', dial: '971' },
  { name: 'Оман', dial: '968' },
  { name: 'Пакистан', dial: '92' },
  { name: 'Палау', dial: '680' },
  { name: 'Панама', dial: '507' },
  { name: 'Папуа — Новая Гвинея', dial: '675' },
  { name: 'Парагвай', dial: '595' },
  { name: 'Перу', dial: '51' },
  { name: 'Польша', dial: '48' },
  { name: 'Португалия', dial: '351' },
  { name: 'Россия', dial: '7' },
  { name: 'Руанда', dial: '250' },
  { name: 'Румыния', dial: '40' },
  { name: 'Сальвадор', dial: '503' },
  { name: 'Самоа', dial: '685' },
  { name: 'Сан-Марино', dial: '378' },
  { name: 'Сан-Томе и Принсипи', dial: '239' },
  { name: 'Саудовская Аравия', dial: '966' },
  { name: 'Северная Македония', dial: '389' },
  { name: 'Сейшелы', dial: '248' },
  { name: 'Сенегал', dial: '221' },
  { name: 'Сент-Винсент и Гренадины', dial: '1784' },
  { name: 'Сент-Китс и Невис', dial: '1869' },
  { name: 'Сент-Люсия', dial: '1758' },
  { name: 'Сербия', dial: '381' },
  { name: 'Сингапур', dial: '65' },
  { name: 'Сирия', dial: '963' },
  { name: 'Словакия', dial: '421' },
  { name: 'Словения', dial: '386' },
  { name: 'Соломоновы Острова', dial: '677' },
  { name: 'Сомали', dial: '252' },
  { name: 'Судан', dial: '249' },
  { name: 'Суринам', dial: '597' },
  { name: 'США', dial: '1' },
  { name: 'Сьерра-Леоне', dial: '232' },
  { name: 'Таджикистан', dial: '992' },
  { name: 'Таиланд', dial: '66' },
  { name: 'Танзания', dial: '255' },
  { name: 'Того', dial: '228' },
  { name: 'Тонга', dial: '676' },
  { name: 'Тринидад и Тобаго', dial: '1868' },
  { name: 'Тувалу', dial: '688' },
  { name: 'Тунис', dial: '216' },
  { name: 'Туркменистан', dial: '993' },
  { name: 'Турция', dial: '90' },
  { name: 'Уганда', dial: '256' },
  { name: 'Узбекистан', dial: '998' },
  { name: 'Украина', dial: '380' },
  { name: 'Уругвай', dial: '598' },
  { name: 'Фиджи', dial: '679' },
  { name: 'Филиппины', dial: '63' },
  { name: 'Финляндия', dial: '358' },
  { name: 'Франция', dial: '33' },
  { name: 'Хорватия', dial: '385' },
  { name: 'ЦАР', dial: '236' },
  { name: 'Чад', dial: '235' },
  { name: 'Черногория', dial: '382' },
  { name: 'Чехия', dial: '420' },
  { name: 'Чили', dial: '56' },
  { name: 'Швейцария', dial: '41' },
  { name: 'Швеция', dial: '46' },
  { name: 'Шри-Ланка', dial: '94' },
  { name: 'Эквадор', dial: '593' },
  { name: 'Экваториальная Гвинея', dial: '240' },
  { name: 'Эритрея', dial: '291' },
  { name: 'Эсватини', dial: '268' },
  { name: 'Эстония', dial: '372' },
  { name: 'Эфиопия', dial: '251' },
  { name: 'ЮАР', dial: '27' },
  { name: 'Южная Корея', dial: '82' },
  { name: 'Южный Судан', dial: '211' },
  { name: 'Ямайка', dial: '1876' },
  { name: 'Япония', dial: '81' },
]

export const COUNTRIES: Country[] = [...RAW].sort((a, b) => a.name.localeCompare(b.name, 'ru'))

// Optional city suggestions per country (free text still allowed elsewhere).
export const CITIES: Record<string, string[]> = {
  'Казахстан': ['Астана', 'Алматы', 'Шымкент', 'Караганда', 'Актобе', 'Тараз', 'Павлодар', 'Усть-Каменогорск', 'Семей', 'Атырау', 'Костанай', 'Кызылорда', 'Уральск', 'Петропавловск', 'Актау', 'Темиртау', 'Туркестан', 'Кокшетау', 'Талдыкорган', 'Экибастуз'],
  'Россия': ['Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург', 'Казань', 'Нижний Новгород', 'Челябинск', 'Самара', 'Омск', 'Ростов-на-Дону'],
  'Киргизия': ['Бишкек', 'Ош', 'Джалал-Абад', 'Каракол'],
  'Узбекистан': ['Ташкент', 'Самарканд', 'Бухара', 'Наманган', 'Андижан'],
  'Азербайджан': ['Баку', 'Гянджа', 'Сумгаит'],
  'Грузия': ['Тбилиси', 'Батуми', 'Кутаиси'],
  'Турция': ['Стамбул', 'Анкара', 'Измир', 'Анталья'],
  'Беларусь': ['Минск', 'Гомель', 'Брест'],
  'Украина': ['Киев', 'Харьков', 'Одесса', 'Львов'],
}

export function dialForCountry(name: string): string | null {
  const c = COUNTRIES.find(x => x.name.toLowerCase() === name.trim().toLowerCase())
  return c?.dial ?? null
}
